/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.7.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.smartjob.usersbackend.adapter.in.web.interfaces;

import com.smartjob.usersbackend.adapter.in.web.models.AddUserPayload;
import com.smartjob.usersbackend.adapter.in.web.models.CreatedUserDTO;
import com.smartjob.usersbackend.adapter.in.web.models.ErrorResponse;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", comments = "Generator version: 7.7.0")
@Validated
public interface UsersApi {

    /**
     * POST /v1/users : Add new user
     * Add new user if email does not exist and returns creation details
     *
     * @param addUserPayload AddUserPayload component representing details of user and telephones collection (optional)
     * @return Project List (status code 201)
     *         or Bad request (status code 400)
     *         or Internal Server Error (status code 500)
     */
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/v1/users",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    ResponseEntity<CreatedUserDTO> addUser(
         @Valid @RequestBody(required = false) AddUserPayload addUserPayload
    );

}
